### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for UNetModel: [rank0]: 	Missing key(s) in state_dict: "label_emb.weight". 

### ISSUE THREAD

**Issue by mmitchef** [openai/improved-diffusion#144]
Hi @unixpickle @NoahSchiro 

Thanks for sharing your code. I trained  conditional model by setting `--class_cond True` . But, when I printed class_cond during sampling its value was equal to False and if I pass `--class_cond True` to sampling code it gave me this error `Missing key(s) in state_dict: "label_emb.weight".` 
I followed instruction regarding preparing dataset and renamed samples as label1_x.png, label2_x.png, etc. Do you have any idea where I am making mistake.

**Here is my training script**

```
python scripts/image_train.py --data_dir /iddpm_dataset/
                                                          --image_size 512 \
                                                          --num_channels 32 \
                                                          --class_cond True \
                                                          --num_res_blocks 3 \
                                                          --diffusion_steps 4000 \
                                                          --noise_schedule linear \
                                                          --lr 1e-4 \
                                                          --batch_size 4
```

**Here is my sampling script**
```
python scripts/image_sample.py --model_path /improved-diffusion/results_512/ema_0.9999_4970000.pt \
                                                   --image_size 512 \
                                                   --num_channels 32 \
                                                   --noise_schedule linear \
                                                   --timestep_respacing 500 \
                                                   --class_cond True \

Logging to /tmp/openai-2024-09-03-18-51-59-610229
creating model and diffusion...
/improved-diffusion/improved_diffusion/dist_util.py:63: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return th.load(io.BytesIO(data), **kwargs)
[rank0]: Traceback (most recent call last):
[rank0]:   File "improved-diffusion/scripts/image_sample.py", line 111, in <module>
[rank0]:     main()
[rank0]:   File "/mproved-diffusion/scripts/image_sample.py", line 33, in main
[rank0]:     model.load_state_dict(
[rank0]:   File "anaconda3/envs/improved-diffusion/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for UNetModel:
[rank0]: 	Missing key(s) in state_dict: "label_emb.weight". 
```

**Comment by mmitchef** [comment]
As an update I added `"--num_res_blocks 3"` to the `sampling script` and it solved the problem and I made sure that I have changed number of classes in `script_util.py`

**Comment by mmitchef** [comment]
As an update I added "--num_res_blocks 3" to the python scripts/image_sample.py and made sure that I have changed number of classes in script_util.py. Then, problem was solved. **Note:** for unconditional model you dont need to have "--num_res_blocks 3" as your parameters.
