### ISSUE TITLE
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation

### ISSUE THREAD

**Issue by MeimShang** [openai/improved-diffusion#23]
It's an error when I run image_train.py My torch version is 1.7.1+cu110
Traceback (most recent call last):
  File "scripts/image_train.py", line 83, in <module>
    main()
  File "scripts/image_train.py", line 41, in main
    TrainLoop(
  File "/mnt/e/w2l/code/diffusion/ddim/improved-diffusion-main/improved_diffusion/train_util.py", line 78, in __init__
    self._load_and_sync_parameters()
  File "/mnt/e/w2l/code/diffusion/ddim/improved-diffusion-main/improved_diffusion/train_util.py", line 127, in _load_and_sync_parameters
    dist_util.sync_params(self.model.parameters())
  File "/mnt/e/w2l/code/diffusion/ddim/improved-diffusion-main/improved_diffusion/dist_util.py", line 72, in sync_params
    dist.broadcast(p, 0)
  File "/home/mayme/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 868, in broadcast
    work.wait()
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

**Comment by jinzeren** [comment]
Same problem. Have you found the solution?

**Comment by createvalues** [comment]
I have same problem.if you work in windows,you can solve this problem by this method:
modify sync_params function
![q1](https://github.com/openai/improved-diffusion/assets/78260624/0215f2e0-6980-495c-b0cd-512d7fad8a83)
i guess the problem is that windows donot supports distributed training.
