### ISSUE TITLE
Query: Distributed learning

### ISSUE THREAD

**Issue by KomputerMaster64** [openai/improved-diffusion#24]
I am trying to implement the improved-ddpm project using google colab (1 GPU), I am not sure how to rectify the distributed training problem coming because of the following code

```
Traceback (most recent call last):
  File "image_train.py", line 7, in <module>
    from improved_diffusion import dist_util, logger
  File "/content/gdrive/MyDrive/Colab Notebooks/GitHub Repositories/improved-diffusion/improved_diffusion/dist_util.py", line 10, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
```

**Comment by taoisu** [comment]
Just install mpi4py python package (`pip install mpi4py`), and you may also need to install libmpich-dev (`apt install libmpich-dev`) before that.

**Comment by KomputerMaster64** [comment]
I am still facing issue. I will search more about it. The following is the output:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requests 2.23.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you have urllib3 1.26.11 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.`

**Comment by muhamadusman** [comment]
@KomputerMaster64 you can try with "conda install -c conda-forge mpi4py" it solved the issue for me

**Comment by JunMa11** [comment]
@muhamadusman May i know your mpi4py version?

I got the following error when training the model:

> ImportError: libmpi.so.12: cannot open shared object file: No such file or directory

**Comment by adahfbch** [comment]
> @muhamadusman May i know your mpi4py version?
> 
> I got the following error when training the model:
> 
> > ImportError: libmpi.so.12: cannot open shared object file: No such file or directory

Hi, have you solved this problem? I just got the same error.

**Comment by adahfbch** [comment]
> @muhamadusman May i know your mpi4py version?
> 
> I got the following error when training the model:
> 
> > ImportError: libmpi.so.12: cannot open shared object file: No such file or directory

@JunMa11 Hi, have you solved this problem? I just got the same error.

**Comment by adahfbch** [comment]
> I got the following error when training the model:
> 
> > ImportError: libmpi.so.12: cannot open shared object file: No such file or directory

@JunMa11 Hi, have you solved this problem? I just got the same error.

**Comment by Xujxyang** [comment]
In my case, it can be resolved by doing this:

```bash
conda install mpi4py==3.1.5

**Comment by kliu0010** [comment]
> [@muhamadusman](https://github.com/muhamadusman) May i know your mpi4py version?
> 
> I got the following error when training the model:
> 
> > ImportError: libmpi.so.12: cannot open shared object file: No such file or directory

I encountered the same error after running:
`apt install libmpich-dev`
`pip install mpi4py`

 The following steps resolved it:
`pip uninstall mpi4py`
`pip install openmpi`
`pip install mpi4py`

Hope this helps anyone facing the same issue.

**Comment by kliu0010** [comment]
> > [@muhamadusman](https://github.com/muhamadusman) May i know your mpi4py version?
> > I got the following error when training the model:
> > > ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
> 
> I encountered the same error after running: `apt install libmpich-dev` `pip install mpi4py`
> 
> The following steps resolved it: `pip uninstall mpi4py` `pip install openmpi` `pip install mpi4py`
> 
> Hope this helps anyone facing the same issue.

I later discovered that when running with `mpiexec`, my program would terminate silently without any error message. The issue was resolved by reinstalling `mpi4py` and `openmpi` using `conda` instead of `pip`:
`pip uninstall mpi4py`
`pip uninstall openmpi`
`conda install mpi4py`
`conda install openmpi`
