### ISSUE TITLE
ImportError for MPI

### ISSUE THREAD

**Issue by baniasbaabe** [openai/improved-diffusion#5]
When I run

`python scripts/image_train.py --data_dir path/to/images $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS`

I get the following error:

`Traceback (most recent call last):
  File "scripts/image_train.py", line 7, in <module>
    from guided_diffusion import dist_util, logger
  File "d:\dev\jqs-bb\guided-diffusion\guided_diffusion\dist_util.py", line 10, in <module>
    from mpi4py import MPI
ImportError: DLL load failed while importing MPI: The module was not found
`
I also installed the requirements from the setup.py

**Comment by baniasbaabe** [comment]
Solved it https://stackoverflow.com/questions/14004457/dll-load-failed-the-specified-module-could-not-be-found-when-doing-from-mpi4py
